### ISSUE TITLE
Frozen Laboratory - Diamond

### ISSUE THREAD

**Issue by JimPancakes** [becored/WL4_PW#3]
Me again.

Making a system for diamond completion was an awesome idea. Managed to collect all of them except for this one from Frozen Laboratory:

![Sprite-0002](https://user-images.githubusercontent.com/62670723/141521679-30453ed5-494a-4d96-8264-2c6828bd8755.png)

I've tried everything but still can't manage to get it. 

Also, it's been a real blast playing this. It's clear you put your heart and soul into it. Hope more people get to play it.

**Comment by becored** [comment]
Hey, glad you seem to be enjoying it.

Try this: crouch walk onto the very start of the slope and do the earliest roll possible, hold R and right

It may require some tries, but it should work eventually.

**Comment by JimPancakes** [comment]
> Hey, glad you seem to be enjoying it.
> 
> Try this: crouch walk onto the very start of the slope and do the earliest roll possible, hold R and right
> 
> It may require some tries, but it should work eventually.

It worked. Thanks a bunch!
